# Generated by Django 3.1.3 on 2020-11-27 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('release_year', models.IntegerField(default=2020, validators=[django.core.validators.MinValueValidator(1920), django.core.validators.MaxValueValidator(2020)])),
                ('transmission', models.CharField(choices=[('MCH', 'mechanics'), ('AUT', 'automatic'), ('ROB', 'robotic')], default='MCH', max_length=3)),
                ('color', models.CharField(max_length=150)),
            ],
        ),
    ]
