# Generated by Django 3.1.3 on 2020-11-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Mechanic', 'mechanics'), ('Authomatic', 'automatic'), ('Robotic', 'robotic')], default='Mechanic', max_length=15),
        ),
    ]
